# Generated by Django 3.2.9 on 2021-12-07 13:03

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20211207_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 13, 3, 20, 522074, tzinfo=utc), verbose_name=datetime.datetime(2021, 12, 7, 13, 2, 56, 768765, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 7, 13, 2, 56, 768765, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(default='My default music collection'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(default='Library', max_length=200),
        ),
    ]
