# Generated by Django 3.2.9 on 2021-12-07 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_auto_20211207_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 7, 14, 10, 22, 306030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 7, 14, 10, 22, 306030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='art',
            field=models.ImageField(upload_to='music/art'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/songs'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='users/images')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
