# Generated by Django 3.2.9 on 2021-12-07 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20211207_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 7, 14, 34, 30, 313355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 7, 14, 34, 30, 313355, tzinfo=utc)),
        ),
    ]
