# Generated by Django 3.2.9 on 2021-12-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
