# Generated by Django 3.2.9 on 2021-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='song',
            name='art',
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='source',
            field=models.CharField(choices=[('YT', 'YouTube'), ('SC', 'Soundcloud'), ('SP', 'Spotify')], default='YT', max_length=4),
        ),
    ]
